FROM fedora:latest
MAINTAINER Petro Shevchenko <shevchenko.p.i@gmail.com>
RUN dnf update -y
RUN	dnf install git cmake make automake gcc gcc-c++ -y
RUN mkdir /opt/lib-coap-cpp
COPY scripts/docker/build.sh /opt/lib-coap-cpp
COPY . /opt/lib-coap-cpp
RUN chmod a+x /opt/lib-coap-cpp/build.sh
RUN cd /opt/lib-coap-cpp && ./build.sh